serverConfig:
    tlsEnabled: false
    port: "8010"
    certPath: "/path/to/cert.pem"
    keyPath: "/path/to/key.pem"
MongoDBURI: "mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false"
