serverConfig:
    tlsEnabled: false
    port: "8010"
    certPath: "/path/to/cert.pem"
    keyPath: "/path/to/key.pem"
mysql:
    username: "root"
    password: ""
    host: "localhost"
    dbname: "grpctodo"
