serverConfig:
    tlsEnabled: false
    port: "8010"
    certPath: "/path/to/cert.pem"
    keyPath: "/path/to/key.pem"
dynamoDB:
    region: "ap-south-1"
    table: "todoItems"
    accessKey: "accessKey"
    secretKey: "secretKey"
