serverConfig:
    tlsEnabled: false
    port: "8010"
    certPath: "/path/to/cert.pem"
    keyPath: "/path/to/key.pem"
postgres:
    username: "postgres"
    password: "postgres"
    endpoint: "localhost"
    port: "5432"
    dBName: "grpctodo"
